### ISSUE TITLE
[build] proper dist output

### ISSUE THREAD

**Issue by mixvar** [VirtusLab/formts#37]
research & implement the most appropriate way to generate `/dist` folder to make the lib consumable for widest possible audience.

**Comment by dgreene1** [comment]
I used https://github.com/formium/tsdx for that. It automatically builds esm modules and I think a couple of other types. If you let it scaffold your repo it also handles the correct package.json info so that users are informed which file to get from dist.

I recognize that the repo has already been scaffolded, but it’s a pretty easy lift to scaffold again and then put the src dir back in. Let me know if you need help.

**Comment by mixvar** [comment]
Thanks @dgreene1, It makes sense to look at TSDX. I was sceptical of generating entire repo and went for manual setup but maybe it makes more sense to do as you say. Or we can manually apply build config used by tsdx
